/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as CreatepatientRouteImport } from './routes/createpatient'
import { Route as AuthRouteImport } from './routes/auth'

const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatepatientRoute = CreatepatientRouteImport.update({
  id: '/createpatient',
  path: '/createpatient',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/createpatient': typeof CreatepatientRoute
  '/receptionist': typeof ReceptionistRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/createpatient': typeof CreatepatientRoute
  '/receptionist': typeof ReceptionistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/createpatient': typeof CreatepatientRoute
  '/receptionist': typeof ReceptionistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/createpatient' | '/receptionist'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/createpatient' | '/receptionist'
  id: '__root__' | '/auth' | '/createpatient' | '/receptionist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  CreatepatientRoute: typeof CreatepatientRoute
  ReceptionistRoute: typeof ReceptionistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createpatient': {
      id: '/createpatient'
      path: '/createpatient'
      fullPath: '/createpatient'
      preLoaderRoute: typeof CreatepatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  CreatepatientRoute: CreatepatientRoute,
  ReceptionistRoute: ReceptionistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
